const terminalTheme: Record<string, React.CSSProperties> = {
  "hljs": {
    display: "block",
    overflowX: "auto",
    padding: "1em",
    background: "#000000",
    color: "#39FF14",
  },
  "hljs-keyword": { color: "#FFB000" },
  "hljs-built_in": { color: "#FFB000" },
  "hljs-type": { color: "#FFB000" },
  "hljs-literal": { color: "#FFB000" },
  "hljs-number": { color: "#FFB000" },
  "hljs-operator": { color: "#FFB000" },
  "hljs-punctuation": { color: "#39FF14" },
  "hljs-property": { color: "#39FF14" },
  "hljs-regexp": { color: "#FFB000" },
  "hljs-string": { color: "#2bcc10" },
  "hljs-char.escape_": { color: "#2bcc10" },
  "hljs-subst": { color: "#39FF14" },
  "hljs-symbol": { color: "#FFB000" },
  "hljs-variable": { color: "#39FF14" },
  "hljs-variable.language_": { color: "#FFB000" },
  "hljs-variable.constant_": { color: "#FFB000" },
  "hljs-title": { color: "#FFB000" },
  "hljs-title.class_": { color: "#FFB000" },
  "hljs-title.class_.inherited__": { color: "#FFB000" },
  "hljs-title.function_": { color: "#FFB000" },
  "hljs-params": { color: "#39FF14" },
  "hljs-comment": { color: "#1a5c0a" },
  "hljs-doctag": { color: "#FFB000" },
  "hljs-meta": { color: "#FFB000" },
  "hljs-section": { color: "#FFB000" },
  "hljs-tag": { color: "#39FF14" },
  "hljs-name": { color: "#FFB000" },
  "hljs-attr": { color: "#FFB000" },
  "hljs-attribute": { color: "#39FF14" },
  "hljs-bullet": { color: "#FFB000" },
  "hljs-code": { color: "#39FF14" },
  "hljs-emphasis": { fontStyle: "italic", color: "#39FF14" },
  "hljs-strong": { fontWeight: "bold", color: "#FFB000" },
  "hljs-formula": { color: "#FFB000" },
  "hljs-link": { color: "#FFB000" },
  "hljs-quote": { color: "#1a5c0a" },
  "hljs-selector-tag": { color: "#FFB000" },
  "hljs-selector-id": { color: "#FFB000" },
  "hljs-selector-class": { color: "#FFB000" },
  "hljs-selector-attr": { color: "#FFB000" },
  "hljs-selector-pseudo": { color: "#FFB000" },
  "hljs-template-tag": { color: "#39FF14" },
  "hljs-template-variable": { color: "#FFB000" },
  "hljs-addition": { color: "#39FF14", background: "rgba(57, 255, 20, 0.1)" },
  "hljs-deletion": { color: "#FFB000", background: "rgba(255, 176, 0, 0.1)" },
};

export default terminalTheme;
